type LoyaltyPointsList @entity {
  id: Bytes! # trader address
  loyaltyPoints: BigInt! # uint256
  isActive: Boolean! # bool
}

type MarketTrades @entity {
  id: Bytes! # market address
  trades: [Trade!]! @derivedFrom(field: "market")
  settledCohorts: [SettledCohorts!]! @derivedFrom(field: "market")
}

type Trade @entity {
  id: ID! # trade ID
  market: MarketTrades! @link
  trader: Bytes! # trader address
  price: BigInt! # uint256
  settlementTime: BigInt! # uint256
  isActive: Boolean! # bool
}

type SettledCohorts @entity(immutable: true) {
  id: ID! # cohort ID
  cohortSize: BigInt! # uint256
  settlementTime: BigInt! # uint256
  winners: BigInt! # uint256
  market: MarketTrades! @link
  settlementPrice: BigInt # uint256
}

type UserPaidAndClaimed @entity {
  id: Bytes! # trader address
  claimed: BigInt! # uint256
  paid: BigInt! # uint256
}

type MarketTradeSize @entity {
  id: Bytes! # market address
  tradeSize: BigInt! # uint256
}